# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8084
spring.application.name=descuentos-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/descuentos_db
spring.datasource.username=user_descuentos
spring.datasource.password=pass_descuentos
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

app.rabbitmq.exchange=${APP_RABBITMQ_EXCHANGE:descuento_exchange}
app.rabbitmq.routing-key=${APP_RABBITMQ_ROUTING_KEY:descuento_routing_key}
app.rabbitmq.routing.key=${APP_RABBITMQ_ROUTING_KEY:descuento_routing_key}
