# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8084
spring.application.name=descuentos-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/descuentos_db
spring.datasource.username=user_descuentos
spring.datasource.password=pass_descuentos
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
